version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: aprovafeed_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  storage:
    image: minio/minio
    container_name: aprovafeed_minio
    restart: always
    ports:
      - "9000:9000" # Porta da API (o Node vai conversar aqui)
      - "9001:9001" # Porta do Painel Web (para ver as fotos no navegador)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"